# Generated by Django 4.1.7 on 2023-04-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_videocontent_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='link',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_description',
            field=models.CharField(max_length=1000),
        ),
    ]
