# Generated by Django 4.1.7 on 2023-04-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_videocontent_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('1', 'Home'), ('2', 'Latest'), ('3', 'Sports'), ('4', 'Election'), ('5', 'Entertainment'), ('6', 'Technology'), ('7', 'Business'), ('8', 'Education')], max_length=20, null=True)),
                ('title', models.TextField()),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
