# Generated by Django 4.1.7 on 2023-04-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_textcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
