# Generated by Django 4.1.7 on 2023-04-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_textcontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Latest', 'Latest'), ('Sports', 'Sports'), ('Election', 'Election'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Business', 'Business'), ('Education', 'Education')], max_length=20, null=True),
        ),
    ]
